server:
    port: 8081

spring:
    application:
        name: "social"

    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: "380745696820214"
                        client-secret: "88a4a2795108c6a4fd93382be8f0b75"
                    google:
                        client-id: "xxx"
                        client-secret: "xxx"


    jpa:
        database: mysql
        show-sql: true
        generate-ddl: true
        open-in-view: false
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql:localhost:3366/social
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver