server:
  port: 8080

spring:
  application:
    name: "social"

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "3e6a005cd5712bc58005d784bd9f9e0c"
            client-secret: "eKbNfFJ5WJBoIGnDeYOA1ozqfAyZrsTz"
          google:
            client-id: 발급받은 client-id key
            client-secret: 발급받은 client-secret key
          naver:
            client-id: 발급받은 client-id key
            client-secret: 발급받은 client-secret key
          facebook:
            client-id: 발급받은 client-id key
            client-secret: 발급받은 client-secret key


  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/social